version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}aspnetmicroservicescatalogapi
    build:
      context: .
      dockerfile: src/services/AspnetMicroservices.Catalog.API/Dockerfile

volumes:
  mongo_data: